# Generated by Django 4.2.1 on 2023-05-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_location', to='locations.location', verbose_name='Локация доставки')),
                ('pick_up', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_up_location', to='locations.location', verbose_name='Локация погрузки')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
    ]
