# Generated by Django 4.2.1 on 2023-05-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20230525_2244'),
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='locations.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pick_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_up', to='locations.location', verbose_name='Локация'),
        ),
    ]
