# Generated by Django 4.2.1 on 2023-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_alter_cargo_delivery_alter_cargo_pick_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.IntegerField(verbose_name='Вес'),
        ),
    ]
