# Generated by Django 4.2.1 on 2023-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=5, unique=True, verbose_name='Уникальный номер')),
                ('location', models.IntegerField(default=0, verbose_name='Локация')),
                ('load_capacity', models.IntegerField(default=0, verbose_name='Грузоподъемность')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
