# Generated by Django 4.2.1 on 2023-05-25 20:06
import random

from django.db import migrations

from cars.functions import generate_uid_for_car, generate_load_capacity


def create_20_cars(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')
    Location = apps.get_model('locations', 'Location')
    locations = Location.objects.all()
    for i in range(20):
        uid = generate_uid_for_car()
        load_capacity = generate_load_capacity()
        location = random.choice(locations)
        Car.objects.create(uid=uid, load_capacity=load_capacity, location=location.zip_code)


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('locations', '0002_auto_20230525_2244'),
    ]

    operations = [migrations.RunPython(create_20_cars)
    ]
