# Generated by Django 4.2.1 on 2023-05-25 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20230525_2244'),
        ('cars', '0002_auto_20230525_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='uid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный номер'),
        ),
    ]
