# Generated by Django 4.2.1 on 2023-05-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_id_alter_car_location_alter_car_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='load_capacity',
            field=models.IntegerField(verbose_name='Грузоподъемность'),
        ),
    ]
