# Generated by Django 4.2.1 on 2023-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('state_name', models.CharField(max_length=100, verbose_name='Штат')),
                ('zip_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='zip-code')),
                ('lat', models.FloatField(default=0, verbose_name='Широта')),
                ('lng', models.FloatField(default=0, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'локации',
            },
        ),
    ]
