# Generated by Django 4.2.1 on 2023-05-25 13:57

from django.db import migrations
from cars.functions import load_data


def combine_locations(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')

    location_list = load_data("uszips.csv")

    for row in location_list:

        Location.objects.create(city=row[3], state_name=row[5], zip_code=row[0], lat=row[1], lng=row[2])


class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [migrations.RunPython(combine_locations)
                  ]
